### ISSUE TITLE
Media query not visible Chrome Beta

### ISSUE THREAD

**Issue by ionutvmi** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#117]
http://puu.sh/fZjKD/eb1f7478cb.png

**Comment by mauricecruz** [comment]
fixed in v. 1.6.7 which should be on the webstore shortly.

**Comment by ionutvmi** [comment]
Still not fixed for me
http://puu.sh/fZObw/b491d75861.png

Chrome version: 41.0.2272.53 beta-m (64-bit)
DevTools Theme: Zero Dark Matrix 1.6.8

**Comment by mauricecruz** [comment]
hmm seems to be a selector different between stable .. beta.. and canary. I normally don't support beta and dev versions, but this kinda makes it hard to use.

Fixed in v. 1.6.9.

**Comment by ionutvmi** [comment]
Thank you
