### ISSUE TITLE
Many broken styles and functionality on last Canary (Mac)

### ISSUE THREAD

**Issue by LeonardoGentile** [mauricecruz/chrome-devtools-zerodarkmatrix-theme#120]
Hello,
thanks for your work once again!
I'm on Mac  43.0.2343.5 canary (64-bit), after the last (or maybe before?) update something doesn't work properly
- the infobox when hovering over a property is not properly displayed (a white box surrounds it and the up arrow is not correctly place)
- sometimes something similar to #116 happens
- some colors have changed making things difficult to read
- I can't read some properties values. In particular some of (not all) those whose value is `...` meaning that there is long string/function/structure/whatever to display. Clicking on the `...` nothing happens

![screen_shot_2015-03-25_at_13_07_44](https://cloud.githubusercontent.com/assets/412061/6824177/021bebca-d2f0-11e4-88ef-217e3056d89a.png)

**Comment by LeonardoGentile** [comment]
Also these lines appeared in the console

![screen_shot_2015-03-25_at_14_57_56](https://cloud.githubusercontent.com/assets/412061/6826356/2b1f38e0-d301-11e4-8003-8b17f00fd081.png)

**Comment by mauricecruz** [comment]
Thanks for the info! Will try to get to it this week!

**Comment by mauricecruz** [comment]
Should be fixed in v.1.7.2. Please verify.

![image](https://cloud.githubusercontent.com/assets/1640686/6841521/4bb218be-d362-11e4-8451-5e3f84ec6dbb.png)

![image](https://cloud.githubusercontent.com/assets/1640686/6841535/7dcbfc02-d362-11e4-90fd-607ca78ca6ae.png)

**Comment by eldonzo** [comment]
1.7.3 here with 43.0.2343.5 canary (64-bit) on Windows 7, I still see all the style issues...

**Comment by LeonardoGentile** [comment]
@mauricecruz I was already using 1.7.3

**Comment by mauricecruz** [comment]
@LeonardoGentile I pushed out 1.7.3 after I wrote the comment above. It's fairly new. Let me know if it's still a problem.

**Comment by LeonardoGentile** [comment]
I double checked, I had already installed a version numbered 1.7.3
I removed it, went to the chrome store, re-installed, now it is still 1.7.3 but it works!

Maybe there was a mistake in some configuration files about the previous version? Not sure, but now seems to work better, I'll keep on testing and I'll keep up to date if I notice anything wrong.

Thank you very much

**Comment by mauricecruz** [comment]
Oddly enough, I think that's happened before. I updated the devtools version used to check between loading the canary.css and stable.css. That's the only difference I can think that would've caused this. ::shrug::

Let me know if you find anything else!

**Comment by mauricecruz** [comment]
I think we're good here right?

**Comment by LeonardoGentile** [comment]
:+1:
